version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gochat
      POSTGRES_USER: todayblue
      POSTGRES_PASSWORD: password1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: